name: run-tests
on:
  pull_request:
    paths:
      - 'src/app/*'
      - '.github/workflows/run-tests.yml'
jobs:
  run-tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: npm install
      - name: run tests
        run: ng test
